### ISSUE TITLE
Vila报错如何解决？

### ISSUE THREAD

**Issue by Yhc-777** [sophgo/sophon-demo#72]
python3 python/vila.py --llm ./models/BM1688/llama.bmodel --vision ./models/BM1688/vision_embedding.bmodel --video datasets/test_car_person_1080P.mp4 --dev_id 0
[bmlib_memory][error] bm_alloc_gmem failed, dev_id = 0, size = 0x2aa1000
[BM_CHECK][error] BM_CHECK_RET fail /media/oscar/Basislink/BM1688/SDK-1.7/SourceCode/libsophon/bmlib/src/bmlib_memory.cpp: bm_malloc_device_byte_heap_mask_u64: 1228
[BMRT][Register:2210] FATAL:coeff alloc failed, size[0x2aa1000]
[2024-12-10 11:54:02.098] [error] [engine_llm.cpp:838] Load bmodel ./models/BM1688/llama.bmodel failed
Traceback (most recent call last):
  File "python/vila.py", line 273, in <module>
    vila = Vila(args.video, args.llm, args.vision, args.dev_id)
  File "python/vila.py", line 93, in __init__
    self.model = sail.EngineLLM(llm_bmodel_path, [dev_id])
sophon.sail.SailEngineError: EngineLLM related error!

**Comment by BigCircle100** [comment]
您是否有使用readme中提供的sail版本
